CREATE DATABASE O06_EJERCICIO_4_11
GO

USE O06_EJERCICIO_4_11
GO

CREATE TABLE NUMEROS(
ID INT IDENTITY(1,1) NOT NULL,
DESCRIPCION VARCHAR(50)
)
GO


DECLARE @CONTADOR INT = 1
WHILE @CONTADOR <= 10
BEGIN

       INSERT INTO NUMEROS(DESCRIPCION) VALUES(NULL)
	   SET @CONTADOR = @CONTADOR + 1
END


SELECT ID,
        CASE 
		    WHEN ID IN (1,3,5,7,9) THEN 'EL NUMERO ES IMPAR'
			WHEN ID IN (2,4,6,8,10) THEN 'EL NUMERO ES PAR'
			END AS DESCRIPCION
FROM NUMEROS

SELECT ID,
CASE
            WHEN ID = 1 THEN ''
			WHEN ID = 3 THEN ''
			WHEN ID = 5 THEN ''
			WHEN ID = 7 THEN ''
			WHEN ID = 9 THEN 'EL NUMERO ES IMPAR'
			WHEN ID = 2 THEN ''
			WHEN ID = 4 THEN ''
			WHEN ID = 6 THEN ''
			WHEN ID = 8 THEN ''
			WHEN ID = 10 THEN 'EL NUMERO ES PAR'
END DESCRIPCION
from NUMEROS


UPDATE NUMEROS
SET DESCRIPCION = case
                      when ID IN (1, 3, 5, 7, 9) THEN 'EL NUMERO ES IMPAR'
					  when ID IN (2, 4, 6, 8, 10) THEN 'EL NUMERO ES PAR'
              END


			  SELECT * FROM NUMEROS