CREATE DATABASE EJERCICIO_4_16
GO

USE EJERCICIO_4_16
GO

-- CREACIÓN TABLA
CREATE TABLE VALORES(
	ID INT IDENTITY(1,1)PRIMARY KEY,
	VALOR_A INT,
	VALOR_B INT,
	VALOR_C INT,
	MAYOR_LETRA VARCHAR(5),
	MAYOR_VALOR INT,
	MENOR_LETRA VARCHAR(5),
	MENOR_VALOR INT
)
-- INSERTAR VALORES
INSERT VALORES(VALOR_A,VALOR_B,VALOR_C)VALUES(1,2,3)
INSERT VALORES(VALOR_A,VALOR_B,VALOR_C)VALUES(4,6,5)
INSERT VALORES(VALOR_A,VALOR_B,VALOR_C)VALUES(9,7,6)
INSERT VALORES(VALOR_A,VALOR_B,VALOR_C)VALUES(12,11,10)
INSERT VALORES(VALOR_A,VALOR_B,VALOR_C)VALUES(13,15,14)
INSERT VALORES(VALOR_A,VALOR_B,VALOR_C)VALUES(16,17,18)
INSERT VALORES(VALOR_A,VALOR_B,VALOR_C)VALUES(19,21,20)
-- REFRESCAR
-- FUNCIONALIDAD CON CASE EN UPDATE 'MAYOR_LETRA'
UPDATE VALORES
SET    MAYOR_LETRA = CASE
						WHEN VALOR_A > VALOR_B THEN
													CASE
														WHEN VALOR_A > VALOR_C THEN 'A'
														ELSE 'C'
													END
						ELSE
							CASE
								WHEN VALOR_B > VALOR_C THEN 'B'
								ELSE 'C'
							END
						END
-- FUNCIONALIDAD CON CASE EN UPDATE 'MAYOR_VALOR'
UPDATE VALORES
SET    MAYOR_VALOR = CASE
						WHEN VALOR_A > VALOR_B THEN
													CASE
														WHEN VALOR_A > VALOR_C THEN VALOR_A
														ELSE VALOR_C
													END
						ELSE
							CASE
								WHEN VALOR_B > VALOR_C THEN VALOR_B
								ELSE VALOR_C
							END
						END
-- FUNCIONALIDAD CON CASE EN UPDATE 'MENOR_VALOR'
UPDATE VALORES
SET    MENOR_VALOR = CASE
						WHEN VALOR_A < VALOR_B THEN
													CASE
														WHEN VALOR_A < VALOR_C THEN VALOR_A
														ELSE VALOR_C
													END
						ELSE
							CASE
								WHEN VALOR_B < VALOR_C THEN VALOR_B
								ELSE VALOR_C
							END
						END
-- FUNCIONALIDAD CON CASE EN UPDATE 'MENOR_LETRA'
UPDATE VALORES
SET    MENOR_LETRA = CASE
						WHEN VALOR_A < VALOR_B THEN
													CASE
														WHEN VALOR_A < VALOR_C THEN 'A'
														ELSE 'C'
													END
						ELSE
							CASE
								WHEN VALOR_B < VALOR_C THEN 'B'
								ELSE 'C'
							END
						END
-- VISUALIZAR REGISTROS
SELECT * FROM VALORES