CREATE DATABASE EJERCICIO_3_18
GO

USE EJERCICIO_3_18
GO

--Crear tabla
CREATE TABLE MAYOR
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	VALOR_A INT,
	VALOR_B INT,
	VALOR_C INT,
	MAYOR_LETRA VARCHAR(10),
	MAYOR_VALOR INT
)
GO

--Insertar Valores
INSERT MAYOR(VALOR_A,VALOR_B,VALOR_C) VALUES (3,2,1)
INSERT MAYOR(VALOR_A,VALOR_B,VALOR_C) VALUES (3,1,2)
INSERT MAYOR(VALOR_A,VALOR_B,VALOR_C) VALUES (2,3,1)
INSERT MAYOR(VALOR_A,VALOR_B,VALOR_C) VALUES (2,1,3)
INSERT MAYOR(VALOR_A,VALOR_B,VALOR_C) VALUES (1,2,3)
INSERT MAYOR(VALOR_A,VALOR_B,VALOR_C) VALUES (1,3,2)


SELECT * FROM MAYOR

--Actualizar tablas 
UPDATE MAYOR
SET MAYOR_VALOR = CASE 
					WHEN VALOR_A > VALOR_B THEN 
												CASE
													WHEN VALOR_A > VALOR_C THEN VALOR_A
													ELSE VALOR_C 
												END
											 ELSE
												CASE WHEN VALOR_B > VALOR_C THEN VALOR_B
													 ELSE VALOR_C 
												END
											END
GO

UPDATE MAYOR
SET MAYOR_LETRA = CASE 
					WHEN VALOR_A > VALOR_B THEN 
												CASE
													WHEN VALOR_A > VALOR_C THEN 'A'
													ELSE 'C'
												END
											 ELSE
												CASE WHEN VALOR_B > VALOR_C THEN 'B'
													 ELSE 'C' 
												END
											END
GO

--Funciones de MAYORLETRA Y MAYORVALOR

ALTER FUNCTION DBO.MAYORLETRA(@VALOR_A INT,@VALOR_B INT,@VALOR_C INT)
RETURNS VARCHAR
AS
BEGIN
	DECLARE @MAYOR_LETRA VARCHAR
	SET @MAYOR_LETRA = CASE 
					WHEN @VALOR_A > @VALOR_B THEN 
												CASE
													WHEN @VALOR_A > @VALOR_C THEN 'A'
													ELSE 'C'
												END
											 ELSE
												CASE WHEN @VALOR_B > @VALOR_C THEN 'B'
													 ELSE 'C' 
												END
											END
   RETURN @MAYOR_LETRA;
END
GO

ALTER FUNCTION DBO.MAYORVALOR(@VALOR_A INT,@VALOR_B INT,@VALOR_C INT)
RETURNS INT
AS
BEGIN
	DECLARE @MAYOR_VALOR INT
	SET @MAYOR_VALOR = CASE 
					WHEN @VALOR_A > @VALOR_B THEN 
												CASE
													WHEN @VALOR_A > @VALOR_C THEN @VALOR_A
													ELSE @VALOR_C 
												END
											 ELSE
												CASE WHEN @VALOR_B > @VALOR_C THEN @VALOR_B
													 ELSE @VALOR_C 
												END
											END
   RETURN  @MAYOR_VALOR;
END
GO

--Actualizar con funciones ya definidas
UPDATE MAYOR
SET MAYOR_LETRA = DBO.MAYORLETRA(VALOR_A,VALOR_B,VALOR_C)
GO

UPDATE MAYOR
SET MAYOR_VALOR = DBO.MAYORVALOR(VALOR_A,VALOR_B,VALOR_C)

SELECT * FROM MAYOR