CREATE DATABASE EJERCICIO_4_4
GO

use EJERCICIO_4_4

go

-- CREACIÓN TABLAS
CREATE TABLE ESTUDIANTES
(
	ID INT IDENTITY(1,1)PRIMARY KEY,
	NOMBRE VARCHAR(50),
	PROMEDIO DECIMAL(10,2)
)
CREATE TABLE PROMEDIO_SEMESTRE
(
	ID_ESTUDIANTE INT,
	ID_SEMESTRE INT,
	PROMEDIO DECIMAL(10,2) 
)
CREATE TABLE CALIFICACIONES
(
	ID INT IDENTITY(1,1)PRIMARY KEY,
	ID_ESTUDIANTE INT,
	SEMESTRE INT,
	MATERIA VARCHAR(20),
	CALIFICACION DECIMAL(10,2)
)
----------- REGISTROS TABLAS --------------
-- ESTUDIANTES
INSERT INTO ESTUDIANTES(NOMBRE)VALUES('JUAN PEREZ')
INSERT INTO ESTUDIANTES(NOMBRE)VALUES('MARIA HERNANDEZ')
INSERT INTO ESTUDIANTES(NOMBRE)VALUES('JUANA LOMAS')
INSERT INTO ESTUDIANTES(NOMBRE)VALUES('ELIZABETH MORENO')
INSERT INTO ESTUDIANTES(NOMBRE)VALUES('ALBERTO CHAVEZ')
-- PROMEDIO PRIMER SEMESTRE 
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(1,1,NULL)
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(2,1,NULL)
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(3,1,NULL)
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(4,1,NULL)
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(5,1,NULL)
-- PROMEDIO SEGUNDO SEMESTRE
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(1,2,NULL)
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(2,2,NULL)
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(3,2,NULL)
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(4,2,NULL)
INSERT INTO PROMEDIO_SEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE,PROMEDIO)VALUES(5,2,NULL)
-- PROMEDIO MATERIAS DE 1ER SEMESTRE
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,1,'MATEMATICAS',9.0)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,1,'PROGRAMACIÓN',7.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,1,'TECNOLOGÍAS',9.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,1,'DESARROLLO WEB',5.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,1,'ARQUITECTURA',8.3)

INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,1,'MATEMATICAS',5.0)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,1,'PROGRAMACIÓN',8.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,1,'TECNOLOGÍAS',3.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,1,'DESARROLLO WEB',9.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,1,'ARQUITECTURA',7.4)

INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,1,'MATEMATICAS',6.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,1,'PROGRAMACIÓN',8.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,1,'TECNOLOGÍAS',9.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,1,'DESARROLLO WEB',9.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,1,'ARQUITECTURA',9.6)

INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,1,'MATEMATICAS',9.4)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,1,'PROGRAMACIÓN',8.3)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,1,'TECNOLOGÍAS',9.7)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,1,'DESARROLLO WEB',8.7)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,1,'ARQUITECTURA',8.9)

INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,1,'MATEMATICAS',9.8)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,1,'PROGRAMACIÓN',7.8)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,1,'TECNOLOGÍAS',6.0)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,1,'DESARROLLO WEB',9.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,1,'ARQUITECTURA',7.9)

-- PROMEDIO MATERIAS DE 2DO SEMESTRE
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,2,'MATEMATICAS II',9.0)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,2,'PROGRAMACIÓN II',8.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,2,'TECNOLOGÍAS II',7.0)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,2,'DESARROLLO WEB II',9.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(1,2,'ARQUITECTURA II',9.3)

INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,2,'MATEMATICAS II',8.0)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,2,'PROGRAMACIÓN II',9.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,2,'TECNOLOGÍAS II',6.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,2,'DESARROLLO WEB II',6.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(2,2,'ARQUITECTURA II',9.4)

INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,2,'MATEMATICAS II',9.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,2,'PROGRAMACIÓN II',7.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,2,'TECNOLOGÍAS II',7.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,2,'DESARROLLO WEB II',7.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(3,2,'ARQUITECTURA II',9.9)

INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,2,'MATEMATICAS II',9.9)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,2,'PROGRAMACIÓN II',8.8)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,2,'TECNOLOGÍAS II',9.6)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,2,'DESARROLLO WEB II',9.7)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(4,2,'ARQUITECTURA II',8.5)

INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,2,'MATEMATICAS II',9.8)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,2,'PROGRAMACIÓN II',7.8)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,2,'TECNOLOGÍAS II',6.0)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,2,'DESARROLLO WEB II',9.5)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(5,2,'ARQUITECTURA II',7.9)
INSERT INTO CALIFICACIONES(ID_ESTUDIANTE,SEMESTRE,MATERIA,CALIFICACION)VALUES(6,1,'ARQUITECTURA II',7.9)
-- VISUALIZAR REGISTROS
SELECT * FROM ESTUDIANTES
SELECT * FROM PROMEDIO_SEMESTRE
SELECT * FROM CALIFICACIONES
GO
----------- FUNCIONES --------------
CREATE FUNCTION dbo.GET_PROMEDIOXSEMESTRE(@ID_ESTUDIANTE INT,@ID_SEMESTRE INT)
RETURNS DECIMAL(10,2)
AS
BEGIN
	DECLARE @ID INT
	DECLARE @SUMA DECIMAL(10,2)
	DECLARE @CALIFICACION DECIMAL(10,2)
	DECLARE @NUM_CALIFICACION INT
	DECLARE @ID_MAX INT

	SET @ID = NULL
	SELECT @ID = MIN(ID) FROM CALIFICACIONES WHERE ID_ESTUDIANTE = @ID_ESTUDIANTE AND SEMESTRE = @ID_SEMESTRE

	SET @ID_MAX = NULL
	SELECT @ID_MAX = MAX(ID) FROM CALIFICACIONES WHERE ID_ESTUDIANTE = @ID_ESTUDIANTE AND SEMESTRE = @ID_SEMESTRE

	SET @SUMA = 0

	SET @CALIFICACION = NULL

	SET @NUM_CALIFICACION = 0

	WHILE @ID <= @ID_MAX
	BEGIN
		SET @CALIFICACION = NULL

		SELECT @CALIFICACION = CALIFICACION FROM CALIFICACIONES WHERE ID_ESTUDIANTE = @ID_ESTUDIANTE AND SEMESTRE = @ID_SEMESTRE AND ID = @ID

		IF @CALIFICACION IS NOT NULL
		BEGIN
			SET @SUMA = @SUMA + @CALIFICACION
			
			SET @NUM_CALIFICACION = @NUM_CALIFICACION + 1
		END
		SET @ID = @ID + 1
	END
	DECLARE @RESULTADO DECIMAL(10,2) 
	IF @NUM_CALIFICACION <> 0
	BEGIN
		SET @RESULTADO = @SUMA / @NUM_CALIFICACION
	END
	ELSE
	BEGIN
		SET @RESULTADO = 0;
	END
	RETURN @RESULTADO;
END
-- FUNCIÓN PROMEDIO GENERAL

-- REFRESCAR POR FUNCIÓN
UPDATE PROMEDIO_SEMESTRE
SET	   PROMEDIO = dbo.GET_PROMEDIOXSEMESTRE(ID_ESTUDIANTE,ID_SEMESTRE)
-- UTILIZANDO INNER JOIN (UNION DE TABLAS) ESTUDIANTES VS PROMEDIO_SEMESTRE
SELECT  ESTUDIANTES.ID, ESTUDIANTES.NOMBRE, PROMEDIO_SEMESTRE.ID_SEMESTRE, PROMEDIO_SEMESTRE.PROMEDIO
FROM	ESTUDIANTES INNER JOIN PROMEDIO_SEMESTRE ON ESTUDIANTES.ID = PROMEDIO_SEMESTRE.ID_ESTUDIANTE
WHERE	ESTUDIANTES.ID = 1
-- UTILIZANDO JOINS PROMEDIO_SEMESTRE VS CALIFICACIONES
SELECT * 
FROM	PROMEDIO_SEMESTRE INNER JOIN CALIFICACIONES
		ON PROMEDIO_SEMESTRE.ID_ESTUDIANTE = CALIFICACIONES.ID_ESTUDIANTE
		AND PROMEDIO_SEMESTRE.ID_SEMESTRE = CALIFICACIONES.SEMESTRE
WHERE	PROMEDIO_SEMESTRE.ID_ESTUDIANTE = 1 AND PROMEDIO_SEMESTRE.ID_SEMESTRE = 2
-- AGRUPACIONES
SELECT		ID_ESTUDIANTE, COUNT(*)--CONTABILIZAR REGISTROS
FROM		CALIFICACIONES
GROUP BY	ID_ESTUDIANTE

SELECT		MATERIA, COUNT(*)--CONTABILIZAR REGISTROS
FROM		CALIFICACIONES
GROUP BY	MATERIA

SELECT		SEMESTRE, MATERIA,COUNT(*)
FROM		CALIFICACIONES
GROUP BY	SEMESTRE, MATERIA
ORDER BY 1
SELECT		PROMEDIO,COUNT(*)
FROM		PROMEDIO_SEMESTRE
GROUP BY	PROMEDIO
-- CONSULTA EN PROMEDIO_SEMESTRE
SELECT	PROMEDIO_SEMESTRE.ID_ESTUDIANTE,
		PROMEDIO_SEMESTRE.ID_SEMESTRE,
		MATERIAS_PROMEDIO.PROMEDIO
FROM	PROMEDIO_SEMESTRE 
		INNER JOIN (SELECT	ID_ESTUDIANTE, SEMESTRE, AVG(CALIFICACION) AS PROMEDIO
					FROM	CALIFICACIONES
					GROUP BY ID_ESTUDIANTE, SEMESTRE) AS MATERIAS_PROMEDIO
				ON	PROMEDIO_SEMESTRE.ID_ESTUDIANTE = MATERIAS_PROMEDIO.ID_ESTUDIANTE
				AND PROMEDIO_SEMESTRE.ID_SEMESTRE = MATERIAS_PROMEDIO.SEMESTRE
WHERE	PROMEDIO_SEMESTRE.ID_ESTUDIANTE = 1 AND PROMEDIO_SEMESTRE.ID_SEMESTRE = 2
-- UPDATE EN PROMEDIO_SEMESTRE
UPDATE	PROMEDIO_SEMESTRE
SET		PROMEDIO = subQuery.PROMEDIO
FROM	(SELECT	ID_ESTUDIANTE, SEMESTRE, AVG(CALIFICACION) AS PROMEDIO
		FROM	CALIFICACIONES
		GROUP BY ID_ESTUDIANTE, SEMESTRE) AS subQuery
WHERE	PROMEDIO_SEMESTRE.ID_ESTUDIANTE = subQuery.ID_ESTUDIANTE
		AND PROMEDIO_SEMESTRE.ID_SEMESTRE = subQuery.SEMESTRE
-- CONSULTA EN PROMEDIO ESTUDIANTES
SELECT	PS.ID_ESTUDIANTE, AVG(PROMEDIO) AS PROMEDIO_GENERAL
FROM	PROMEDIO_SEMESTRE PS
WHERE	PS.ID_SEMESTRE BETWEEN 1 AND 2
GROUP BY PS.ID_ESTUDIANTE	
-- UPDATE EN PROMEDIO ESTUDIANTES
UPDATE	ESTUDIANTES
SET		PROMEDIO = subQuery.PROMEDIO_GENERAL
FROM	(SELECT	PS.ID_ESTUDIANTE, AVG(PROMEDIO) AS PROMEDIO_GENERAL
		FROM	PROMEDIO_SEMESTRE PS
		WHERE	PS.ID_SEMESTRE BETWEEN 1 AND 2
		GROUP BY PS.ID_ESTUDIANTE) AS subQuery
WHERE	ID = subQuery.ID_ESTUDIANTE
-- VISUALIZAR REGISTROS
SELECT * FROM ESTUDIANTES
SELECT * FROM PROMEDIO_SEMESTRE
SELECT * FROM CALIFICACIONES
-- FRAGMENTO CONTABILIZAR SEMESTRE EN ESTUDIANTES
SELECT	ID_ESTUDIANTE, COUNT(PROMEDIO)
FROM	PROMEDIO_SEMESTRE
WHERE	ID_SEMESTRE BETWEEN 1 AND 2 
GROUP BY ID_ESTUDIANTE